#!/usr/bin/env bash

# Desktop Ecosystem
sudo pacman -S --noconfirm --needed brightnessctl libnotify ttf-jetbrains-mono-nerd otf-font-awesome 
sudo pacman -S --noconfirm --needed bluez bluez-utils bluetui
sudo pacman -S --noconfirm --needed pavucontrol

# Terminal Ecosystem
sudo pacman -S --noconfirm --needed git github-cli man wl-clipboard

# Hypr Ecosystem
sudo pacman -S --noconfirm --needed hyprpaper hypridle hyprlock hyprsunset

# GUI Applications
sudo pacman -S --noconfirm --needed obsidian
yay -S --noconfirm --needed zotero
yay -S --noconfirm --needed librewolf 
